spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/bookvaultdb
    username: postgres
    password: postgres
    initialization-mode: always
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  flyway:
    enabled: true
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/bookvaultdb
    baselineOnMigrate: true
    schemas: public
    defaultSchema: public
    validateOnMigrate: false
environment: production